AWSTemplateFormatVersion: '2010-09-09'
Description: 'Compute Infrastructure for VIT Learning Platform'

Parameters:
  EnvironmentName:
    Type: String
    Default: Production

Resources:
  WebServerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-web-server
      LaunchTemplateData:
        InstanceType: t3.micro
