AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network Infrastructure for VIT Learning Platform'

Parameters:
  EnvironmentName:
    Type: String
    Default: Production

Resources:
  VITEducationVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
