AWSTemplateFormatVersion: '2010-09-09'
Description: 'Storage Infrastructure for VIT Learning Platform'

Parameters:
  EnvironmentName:
    Type: String
    Default: Production

Resources:
  CourseContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-course-content-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
